language: perl
perl:
  - "5.28"
  - "5.30"
  - "dev"
  - "blead"
matrix:
  include:
    - perl: 5.30
    - env: COVERAGE=1

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
install:
  - cpan-install --deps
  - cpan-install --coverage
before_script:
  - coverage-setup
script:
  - prove -lv
after_success:
    - coverage-report
